import type { Metadata } from "next";
// import { Roboto, Roboto_Slab } from "next/font/google";

import "./globals.css";
import SocialShare from "@/components/Shared/Social/SocialShare";
import Navbar from "@/components/Shared/Navbar";
import Footer from "@/components/Shared/Footer/Footer";

// const roboto = Roboto({
//   variable: "--font-roboto",
//   subsets: ["latin"],
//   weight: ["100", "300", "400", "500", "700", "900"],
// });

// const robotoSlab = Roboto_Slab({
//   variable: "--font-roboto-slab",
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      {/* ${roboto.variable} ${robotoSlab.variable}  */}
      <body className={`antialiased`}>
        <SocialShare />
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
